import { publicProfiles } from '../../db/schema.js';
import { asString } from '../shared/helpers.js';
import {
    normalizePublicProfileBusinessHours,
    normalizePublicProfileSocialLinks,
} from './normalize.js';
import type {
    PublicProfileAccountKind,
    PublicProfileRecord,
    VerticalType,
} from './types.js';

export function mapPublicProfileRow(profile: typeof publicProfiles.$inferSelect): PublicProfileRecord {
    return {
        id: profile.id,
        accountId: profile.accountId ?? null,
        userId: profile.userId,
        vertical: profile.vertical as VerticalType,
        slug: profile.slug,
        isPublished: Boolean(profile.isPublished),
        accountKind: profile.accountKind as PublicProfileAccountKind,
        operatorSubtype: profile.operatorSubtype ?? null,
        operatorSubtypeCustom: profile.operatorSubtypeCustom ?? null,
        displayName: profile.displayName,
        headline: profile.headline ?? null,
        bio: profile.bio ?? null,
        companyName: profile.companyName ?? null,
        website: profile.website ?? null,
        publicEmail: profile.publicEmail ?? null,
        publicPhone: profile.publicPhone ?? null,
        publicWhatsapp: profile.publicWhatsapp ?? null,
        addressLine: profile.addressLine ?? null,
        primaryAddressId: profile.primaryAddressId ?? null,
        city: profile.city ?? null,
        region: profile.region ?? null,
        countryCode: profile.countryCode ?? 'CL',
        regionId: profile.regionId ?? null,
        localityId: profile.localityId ?? null,
        timezone: profile.timezone ?? 'America/Santiago',
        coverImageUrl: profile.coverImageUrl ?? null,
        avatarImageUrl: profile.avatarImageUrl ?? null,
        socialLinks: normalizePublicProfileSocialLinks(profile.socialLinks),
        businessHours: normalizePublicProfileBusinessHours(profile.businessHours),
        specialties: Array.isArray(profile.specialties) ? profile.specialties.map((item) => asString(item)).filter(Boolean) : [],
        scheduleNote: profile.scheduleNote ?? null,
        alwaysOpen: Boolean(profile.alwaysOpen),
        weeklyBreakStart: profile.weeklyBreakStart ?? null,
        weeklyBreakEnd: profile.weeklyBreakEnd ?? null,
    scheduleBlockedSlots: Array.isArray(profile.scheduleBlockedSlots) ? profile.scheduleBlockedSlots : [],
    requiresAdvancePayment: Boolean(profile.requiresAdvancePayment),
    advancePaymentInstructions: profile.advancePaymentInstructions ?? null,
    acceptsTransfer: Boolean(profile.acceptsTransfer),
    acceptsMp: Boolean(profile.acceptsMp),
    acceptsPaymentLink: Boolean(profile.acceptsPaymentLink),
    paymentLinkUrl: profile.paymentLinkUrl ?? null,
    bankTransferData: profile.bankTransferData ?? null,
    mpAccessToken: profile.mpAccessToken ?? null,
    mpUserId: profile.mpUserId ?? null,
    bookingTermsText: profile.bookingTermsText ?? null,
    trialEndsAt: profile.trialEndsAt?.getTime() ?? null,
        createdAt: profile.createdAt.getTime(),
        updatedAt: profile.updatedAt.getTime(),
    };
}
