import type { PanelManifest } from "@simple/shared-types";

export const autosPanelManifest: PanelManifest = {
  vertical: "autos",
  version: "2025.12.27",
  updatedAt: "2025-12-27",
  sidebar: [
    {
      id: "inicio",
      title: "Resumen",
      items: [
        {
          id: "panel",
          label: "Resumen",
          href: "/resumen",
          icon: "dashboard",
          description: "Resumen y alertas del panel",
          status: "active",
        },
      ],
    },
    {
      id: "vender",
      title: "Vender",
      items: [
        {
          id: "new-listing",
          label: "Publicar Vehículo",
          href: "/panel/publicar-vehiculo?new=1",
          icon: "publish",
          description: "Crear una nueva publicación",
          status: "active",
        },
        {
          id: "listings",
          label: "Mis Publicaciones",
          href: "/panel/mis-publicaciones",
          icon: "listings",
          description: "Administra tus publicaciones de vehículos",
          status: "active",
        },
        {
          id: "companies",
          label: "Mi Negocio",
          href: "/panel/mi-negocio",
          icon: "stores",
          description: "Datos de empresa, legal y facturación",
          status: "active",
        },
        {
          id: "public-profile",
          label: "Mi Página",
          href: "/panel/mi-pagina",
          icon: "public-profile",
          description: "Vitrina pública / Mi negocio",
          status: "active",
        },
        {
          id: "mensajes",
          label: "Mensajes",
          href: "/panel/mis-mensajes",
          icon: "messages",
          description: "Chats y leads entrantes",
          status: "active",
        },
        {
          id: "estadisticas",
          label: "Estadísticas",
          href: "/panel/estadisticas",
          icon: "chart",
          description: "Rendimiento de avisos y visitas",
          status: "active",
        },
      ],
    },
    {
      id: "cuenta",
      title: "Cuenta",
      items: [
        {
          id: "profile",
          label: "Mi Perfil",
          href: "/panel/mi-perfil",
          icon: "user",
          description: "Datos personales y credenciales",
          status: "active",
        },
        {
          id: "membership",
          label: "Mis Suscripciones",
          href: "/panel/mis-suscripciones",
          icon: "plans",
          description: "Plan actual, upgrades y renovaciones",
          status: "active",
        },
        {
          id: "favoritos",
          label: "Guardados",
          href: "/panel/guardados",
          icon: "favorites",
          description: "Tus guardados personales",
          status: "active",
        },
        {
          id: "settings",
          label: "Configuraciones",
          href: "/panel/configuraciones",
          icon: "settings",
          description: "Preferencias, integraciones y notificaciones",
          status: "active",
        },
      ],
    },
  ],
  dashboard: [
    {
      id: "health",
      title: "Salud comercial",
      widgets: [
        {
          id: "active_listings",
          type: "kpi",
          title: "Publicaciones activas",
          description: "Vehículos publicados con estado activo",
          dataSource: "listings.activeCount",
          status: "active",
        },
        {
          id: "pending_leads",
          type: "kpi",
          title: "Leads pendientes",
          description: "Contactos sin respuesta",
          dataSource: "leads.pendingCount",
          status: "active",
        },
        {
          id: "avg_response_time",
          type: "kpi",
          title: "Tiempo de respuesta",
          description: "Promedio en horas",
          dataSource: "leads.averageResponseTime",
          status: "beta",
        },
      ],
    },
    {
      id: "pipeline",
      title: "Pipeline y desempeño",
      widgets: [
        {
          id: "lead_sources",
          type: "chart",
          title: "Origen de leads",
          description: "Distribución semanal por canal",
          dataSource: "analytics.leadSources",
          status: "planned",
        },
        {
          id: "conversion_table",
          type: "table",
          title: "Conversiones por ejecutivo",
          description: "Volumen y ratio en los últimos 30 días",
          dataSource: "analytics.teamPerformance",
          status: "planned",
        },
      ],
    },
  ],
  quickActions: [
    {
      id: "quick_publish",
      label: "Publicar Vehículo",
      href: "/panel/publicar-vehiculo?new=1",
      icon: "publish",
      status: "active",
    },
    {
      id: "view_public_profile",
      label: "Ver pagina pública",
      href: "/panel/mi-pagina",
      icon: "public-profile",
      status: "active",
    },
  ],
};
