import type { PanelManifest } from "@simple/shared-types";

export const foodPanelManifest: PanelManifest = {
  vertical: "food",
  version: "2025.12.27",
  updatedAt: "2025-12-27",
  sidebar: [
    {
      id: "inicio",
      title: "Resumen",
      items: [
        {
          id: "panel",
          label: "Resumen",
          href: "/resumen",
          icon: "dashboard",
          description: "Ventas, pedidos y capacidad",
          status: "active",
        },
      ],
    },
    {
      id: "operacion",
      title: "Operación",
      items: [
        {
          id: "restaurants",
          label: "Mi Negocio",
          href: "/panel/empresa",
          icon: "food",
          description: "Locales, horarios y zonas",
          status: "active",
        },
        {
          id: "orders",
          label: "Pedidos",
          href: "/panel/pedidos",
          icon: "orders",
          description: "Pedidos activos y SLA",
          permission: "orders:manage",
          status: "planned",
        },
        {
          id: "kitchen",
          label: "Cocina",
          href: "/panel/cocina",
          icon: "chef",
          description: "Vista de producción en tiempo real",
          status: "planned",
        },
        {
          id: "menu",
          label: "Menú",
          href: "/panel/menu",
          icon: "menu",
          description: "Platos, combos y disponibilidad",
          permission: "menu:edit",
          status: "planned",
        },
        {
          id: "mensajes",
          label: "Mensajes",
          href: "/panel/mensajes",
          icon: "messages",
          description: "Chat y soporte",
          status: "planned",
        },
      ],
    },
    {
      id: "cuenta",
      title: "Cuenta",
      items: [
        {
          id: "profile",
          label: "Mi Perfil",
          href: "/panel/perfil",
          icon: "user",
          description: "Datos del administrador",
          status: "active",
        },
        {
          id: "subscription",
          label: "Mis Suscripciones",
          href: "/panel/suscripcion",
          icon: "billing",
          description: "Planes y cobros",
          status: "planned",
        },
        {
          id: "favoritos",
          label: "Guardados",
          href: "/panel/favoritos",
          icon: "favorites",
          description: "Tus guardados personales",
          status: "planned",
        },
        {
          id: "settings",
          label: "Configuraciones",
          href: "/panel/configuraciones",
          icon: "settings",
          description: "Impuestos, propinas y servicios",
          status: "planned",
        },
      ],
    },
  ],
  dashboard: [
    {
      id: "ventas",
      title: "Ventas y SLA",
      widgets: [
        {
          id: "daily_orders",
          type: "kpi",
          title: "Pedidos del día",
          description: "Pedidos confirmados en las últimas 24h",
          dataSource: "orders.dailyCount",
          status: "planned",
        },
        {
          id: "avg_preparation_time",
          type: "kpi",
          title: "Tiempo de preparación",
          description: "Promedio en minutos",
          dataSource: "kitchen.avgPrepTime",
          status: "planned",
        },
        {
          id: "cancellation_rate",
          type: "kpi",
          title: "Cancelaciones",
          description: "Ratio pedidos cancelados",
          dataSource: "orders.cancellationRate",
          status: "planned",
        },
      ],
    },
    {
      id: "operacion",
      title: "Operación",
      widgets: [
        {
          id: "top_menu_items",
          type: "table",
          title: "Platos destacados",
          description: "Los más vendidos del día",
          dataSource: "menu.topItems",
          status: "planned",
        },
        {
          id: "delivery_heatmap",
          type: "chart",
          title: "Heatmap de entregas",
          description: "Volumen por comuna",
          dataSource: "analytics.deliveryHeatmap",
          status: "planned",
        },
      ],
    },
  ],
  quickActions: [
    {
      id: "add_restaurant",
      label: "Crear restaurante",
      href: "/panel/empresa/nuevo",
      icon: "food",
      status: "planned",
    },
    {
      id: "publish_menu",
      label: "Publicar menú",
      href: "/panel/menu/nuevo",
      icon: "menu",
      status: "planned",
    },
  ],
};
