import type { PanelManifest } from "@simple/shared-types";

export const propertiesPanelManifest: PanelManifest = {
  vertical: "properties",
  version: "2025.12.27",
  updatedAt: "2025-12-27",
  sidebar: [
    {
      id: "inicio",
      title: "Resumen",
      items: [
        {
          id: "panel",
          label: "Resumen",
          href: "/resumen",
          icon: "dashboard",
          description: "Resumen y alertas del panel",
          status: "active",
        },
      ],
    },
    {
      id: "vender",
      title: "Vender",
      items: [
        {
          id: "company",
          label: "Mi Negocio",
          href: "/panel/empresa",
          icon: "stores",
          description: "Equipos, oficinas y permisos",
          status: "active",
        },
        {
          id: "listings",
          label: "Mis Publicaciones",
          href: "/panel/publicaciones",
          icon: "properties",
          description: "Administración de propiedades en venta y arriendo",
          permission: "listings:read",
          status: "active",
        },
        {
          id: "new-listing",
          label: "Publicar Propiedad",
          href: "/panel/nueva-publicacion",
          icon: "publish",
          description: "Formulario único para propiedades",
          permission: "listings:create",
          status: "active",
        },
        {
          id: "public-profile",
          label: "Mi Página",
          href: "/panel/mi-pagina",
          icon: "public-profile",
          description: "Vitrina pública / Mi negocio",
          status: "active",
        },
        {
          id: "mensajes",
          label: "Mensajes",
          href: "/panel/mensajes",
          icon: "messages",
          description: "Consultas provenientes del sitio",
          status: "active",
        },
        {
          id: "estadisticas",
          label: "Estadísticas",
          href: "/panel/estadisticas",
          icon: "chart",
          description: "Performance por canal y equipo",
          permission: "analytics:view",
          status: "planned",
        },
      ],
    },
    {
      id: "cuenta",
      title: "Cuenta",
      items: [
        {
          id: "profile",
          label: "Mi Perfil",
          href: "/panel/perfil",
          icon: "user",
          description: "Datos del usuario y notificaciones",
          status: "active",
        },
        {
          id: "subscription",
          label: "Mis Suscripciones",
          href: "/panel/suscripcion",
          icon: "billing",
          description: "Planes y facturación",
          status: "planned",
        },
        {
          id: "favoritos",
          label: "Guardados",
          href: "/panel/favoritos",
          icon: "favorites",
          description: "Tus guardados personales",
          status: "planned",
        },
        {
          id: "settings",
          label: "Configuraciones",
          href: "/panel/configuraciones",
          icon: "settings",
          description: "Preferencias del marketplace",
          status: "planned",
        },
      ],
    },
  ],
  dashboard: [
    {
      id: "portfolio_health",
      title: "Salud del portafolio",
      widgets: [
        {
          id: "active_properties",
          type: "kpi",
          title: "Propiedades activas",
          description: "Inventario disponible",
          dataSource: "listings.activeCount",
          status: "planned",
        },
        {
          id: "occupied_units",
          type: "kpi",
          title: "Ocupación",
          description: "Porcentaje arrendado vs total",
          dataSource: "analytics.occupancyRate",
          status: "planned",
        },
        {
          id: "avg_days_market",
          type: "kpi",
          title: "Días en vitrina",
          description: "Tiempo promedio para cerrar",
          dataSource: "analytics.daysOnMarket",
          status: "planned",
        },
      ],
    },
    {
      id: "demand",
      title: "Demanda y leads",
      widgets: [
        {
          id: "visit_requests",
          type: "chart",
          title: "Solicitudes de visita",
          description: "Tendencia semanal",
          dataSource: "leads.bookingRequests",
          status: "planned",
        },
        {
          id: "owner_pipeline",
          type: "table",
          title: "Pipeline de propietarios",
          description: "Etapas y probabilidades",
          dataSource: "pipeline.owners",
          status: "planned",
        },
      ],
    },
  ],
  quickActions: [
    {
      id: "publish",
      label: "Publicar Propiedad",
      href: "/panel/nueva-publicacion",
      icon: "publish",
      status: "active",
    },
    {
      id: "schedule_visit",
      label: "Registrar visita",
      href: "/panel/agenda",
      icon: "calendar",
      status: "planned",
    },
  ],
};
