import type { PanelManifest } from "@simple/shared-types";

export const storesPanelManifest: PanelManifest = {
  vertical: "stores",
  version: "2025.12.27",
  updatedAt: "2025-12-27",
  sidebar: [
    {
      id: "inicio",
      title: "Resumen",
      items: [
        {
          id: "panel",
          label: "Resumen",
          href: "/resumen",
          icon: "dashboard",
          description: "Métricas clave del panel",
          status: "active",
        },
      ],
    },
    {
      id: "tienda",
      title: "Tienda",
      items: [
        {
          id: "company",
          label: "Mi Negocio",
          href: "/panel/empresa",
          icon: "stores",
          description: "Sucursales físicas y canales",
          status: "active",
        },
        {
          id: "orders",
          label: "Pedidos",
          href: "/panel/pedidos",
          icon: "orders",
          description: "Pedidos pendientes y cumplidos",
          permission: "orders:manage",
          status: "planned",
        },
        {
          id: "catalog",
          label: "Catálogo",
          href: "/panel/catalogo",
          icon: "catalog",
          description: "Productos y variaciones",
          permission: "catalog:edit",
          status: "planned",
        },
        {
          id: "mensajes",
          label: "Mensajes",
          href: "/panel/mensajes",
          icon: "messages",
          description: "Chats y notificaciones",
          status: "planned",
        },
        {
          id: "estadisticas",
          label: "Estadísticas",
          href: "/panel/estadisticas",
          icon: "chart",
          description: "Performance de ventas y canales",
          status: "planned",
        },
      ],
    },
    {
      id: "cuenta",
      title: "Cuenta",
      items: [
        {
          id: "profile",
          label: "Mi Perfil",
          href: "/panel/perfil",
          icon: "user",
          description: "Datos del responsable y branding",
          status: "active",
        },
        {
          id: "subscription",
          label: "Mis Suscripciones",
          href: "/panel/suscripcion",
          icon: "billing",
          description: "Planes y cobros",
          status: "planned",
        },
        {
          id: "favoritos",
          label: "Guardados",
          href: "/panel/favoritos",
          icon: "favorites",
          description: "Tus guardados personales",
          status: "planned",
        },
        {
          id: "settings",
          label: "Configuraciones",
          href: "/panel/configuraciones",
          icon: "settings",
          description: "Impuestos, envíos y dominios",
          status: "planned",
        },
      ],
    },
  ],
  dashboard: [
    {
      id: "ventas",
      title: "Ventas",
      widgets: [
        {
          id: "gmv",
          type: "kpi",
          title: "GMV",
          description: "Ventas brutas últimos 30 días",
          dataSource: "orders.gmv30d",
          status: "planned",
        },
        {
          id: "avg_ticket",
          type: "kpi",
          title: "Ticket promedio",
          description: "CLP promedio por pedido",
          dataSource: "orders.avgTicket",
          status: "planned",
        },
        {
          id: "conversion",
          type: "kpi",
          title: "Conversión",
          description: "Sesiones vs pedidos",
          dataSource: "analytics.conversion",
          status: "planned",
        },
      ],
    },
    {
      id: "operacion",
      title: "Operación",
      widgets: [
        {
          id: "fulfillment",
          type: "chart",
          title: "Fulfillment",
          description: "Cumplimiento por estado",
          dataSource: "orders.fulfillment",
          status: "planned",
        },
        {
          id: "top_skus",
          type: "table",
          title: "Top SKUs",
          description: "Productos con mejor rendimiento",
          dataSource: "catalog.topSkus",
          status: "planned",
        },
      ],
    },
  ],
  quickActions: [
    {
      id: "new_product",
      label: "Agregar producto",
      href: "/panel/catalogo/nuevo",
      icon: "catalog",
      status: "planned",
    },
    {
      id: "new_campaign",
      label: "Crear campaña",
      href: "/panel/campanas/nueva",
      icon: "analytics",
      status: "planned",
    },
  ],
};
