import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeHydration } from "@/components/layout/ThemeHydration";
import "./globals.css";
import "./styles/select-dropdown.css";

import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { ToastProvider } from "@/components/ui/toast/ToastProvider";
import { ThemeProvider } from "next-themes";
import { AuthProvider } from "@/context/AuthContext";
import { NotificationsProvider } from "@/context/NotificationsContext";
import { AuthModalLazy } from '@/components/auth/AuthModalLazy';


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`bg-lightbg text-lighttext dark:bg-darkbg dark:text-darktext ${inter.variable}`}
        suppressHydrationWarning
      >
        <ThemeHydration>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <AuthProvider>
              <ToastProvider>
                <NotificationsProvider>
                  <Header />
                  <AuthModalLazy />
                  {/* Mantener todo el contenido 10px por debajo del header */}
                  <div className="mt-[10px]">{children}</div>
                  <Footer />
                </NotificationsProvider>
              </ToastProvider>
            </AuthProvider>
          </ThemeProvider>
        </ThemeHydration>
      </body>
    </html>
  );
}
