import type { ValuationHistoricalPoint, VehicleValuationFeedRecord } from '../shared/types.js';

export const VEHICLE_VALUATION_FEED_SEED: VehicleValuationFeedRecord[] = [
    {
        id: 'ca-001',
        source: 'chileautos_feed',
        operationType: 'sale',
        vehicleType: 'car',
        brand: 'toyota',
        model: 'rav4',
        version: '2.5 hybrid cvt',
        year: 2022,
        mileageKm: 36500,
        fuelType: 'Híbrido',
        transmission: 'Automática',
        bodyType: 'SUV',
        regionId: 'rm',
        communeId: 'las-condes',
        title: 'Toyota RAV4 2.5 Hybrid CVT 2022',
        price: 27990000,
        currency: 'CLP',
        publishedAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
        addressLabel: 'Las Condes',
        url: null,
    },
    {
        id: 'mlv-001',
        source: 'mercadolibre_vehicles_feed',
        operationType: 'sale',
        vehicleType: 'car',
        brand: 'toyota',
        model: 'rav4',
        version: '2.5 hybrid cvt',
        year: 2022,
        mileageKm: 42100,
        fuelType: 'Híbrido',
        transmission: 'Automática',
        bodyType: 'SUV',
        regionId: 'rm',
        communeId: 'la-florida',
        title: 'Toyota RAV4 Hybrid 2022',
        price: 27290000,
        currency: 'CLP',
        publishedAt: Date.now() - 1000 * 60 * 60 * 24 * 8,
        addressLabel: 'La Florida',
        url: null,
    },
    {
        id: 'yp-001',
        source: 'yapo_feed',
        operationType: 'sale',
        vehicleType: 'car',
        brand: 'chevrolet',
        model: 'captiva',
        version: 'ii ls 2.4l 6mt',
        year: 2013,
        mileageKm: 128000,
        fuelType: 'Bencina',
        transmission: 'Manual',
        bodyType: 'SUV',
        regionId: 'rm',
        communeId: 'santiago',
        title: 'Chevrolet Captiva II LS 2.4 2013',
        price: 6890000,
        currency: 'CLP',
        publishedAt: Date.now() - 1000 * 60 * 60 * 24 * 13,
        addressLabel: 'Santiago Centro',
        url: null,
    },
    {
        id: 'kv-001',
        source: 'kavak_feed',
        operationType: 'sale',
        vehicleType: 'car',
        brand: 'kia',
        model: 'sportage',
        version: 'ex 2.0 at',
        year: 2021,
        mileageKm: 51400,
        fuelType: 'Bencina',
        transmission: 'Automática',
        bodyType: 'SUV',
        regionId: 'rm',
        communeId: 'pudahuel',
        title: 'Kia Sportage EX 2.0 AT 2021',
        price: 19490000,
        currency: 'CLP',
        publishedAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
        addressLabel: 'Pudahuel',
        url: null,
    },
    {
        id: 'ca-002',
        source: 'chileautos_feed',
        operationType: 'sale',
        vehicleType: 'motorcycle',
        brand: 'yamaha',
        model: 'mt-07',
        version: 'abs',
        year: 2023,
        mileageKm: 8600,
        fuelType: 'Bencina',
        transmission: 'Manual',
        bodyType: 'Naked',
        regionId: 'rm',
        communeId: 'nunoa',
        title: 'Yamaha MT-07 ABS 2023',
        price: 7890000,
        currency: 'CLP',
        publishedAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
        addressLabel: 'Ñuñoa',
        url: null,
    },
    {
        id: 'mlv-002',
        source: 'mercadolibre_vehicles_feed',
        operationType: 'sale',
        vehicleType: 'truck',
        brand: 'volvo',
        model: 'fh',
        version: '460 6x2',
        year: 2021,
        mileageKm: 210000,
        fuelType: 'Diésel',
        transmission: 'Automática',
        bodyType: 'Tracto',
        regionId: 'bio',
        communeId: 'concepcion',
        title: 'Volvo FH 460 6x2 2021',
        price: 86900000,
        currency: 'CLP',
        publishedAt: Date.now() - 1000 * 60 * 60 * 24 * 10,
        addressLabel: 'Concepción',
        url: null,
    },
    {
        id: 'ca-003',
        source: 'chileautos_feed',
        operationType: 'sale',
        vehicleType: 'car',
        brand: 'toyota',
        model: 'corolla',
        version: '1.8 cvt',
        year: 2020,
        mileageKm: 58200,
        fuelType: 'Bencina',
        transmission: 'Automática',
        bodyType: 'Sedán',
        regionId: 'rm',
        communeId: 'providencia',
        title: 'Toyota Corolla 1.8 CVT 2020',
        price: 14990000,
        currency: 'CLP',
        publishedAt: Date.now() - 1000 * 60 * 60 * 24 * 6,
        addressLabel: 'Providencia',
        url: null,
    },
    {
        id: 'mlv-003',
        source: 'mercadolibre_vehicles_feed',
        operationType: 'sale',
        vehicleType: 'car',
        brand: 'toyota',
        model: 'yaris',
        version: '1.5 cvt',
        year: 2021,
        mileageKm: 39800,
        fuelType: 'Bencina',
        transmission: 'Automática',
        bodyType: 'Hatchback',
        regionId: 'rm',
        communeId: 'nunoa',
        title: 'Toyota Yaris 1.5 CVT 2021',
        price: 11990000,
        currency: 'CLP',
        publishedAt: Date.now() - 1000 * 60 * 60 * 24 * 7,
        addressLabel: 'Ñuñoa',
        url: null,
    },
    {
        id: 'yp-002',
        source: 'yapo_feed',
        operationType: 'sale',
        vehicleType: 'car',
        brand: 'hyundai',
        model: 'tucson',
        version: '2.0 at',
        year: 2022,
        mileageKm: 33400,
        fuelType: 'Bencina',
        transmission: 'Automática',
        bodyType: 'SUV',
        regionId: 'rm',
        communeId: 'vitacura',
        title: 'Hyundai Tucson 2.0 AT 2022',
        price: 21490000,
        currency: 'CLP',
        publishedAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
        addressLabel: 'Vitacura',
        url: null,
    },
];

export const VEHICLE_VALUATION_HISTORY_SEED: Record<string, ValuationHistoricalPoint[]> = {
    'sale|car|toyota|rav4|rm|las-condes': [
        { ts: Date.now() - 1000 * 60 * 60 * 24 * 120, medianPrice: 26500000, medianPricePerM2: null, sampleSize: 12 },
        { ts: Date.now() - 1000 * 60 * 60 * 24 * 90, medianPrice: 26900000, medianPricePerM2: null, sampleSize: 14 },
        { ts: Date.now() - 1000 * 60 * 60 * 24 * 60, medianPrice: 27200000, medianPricePerM2: null, sampleSize: 16 },
        { ts: Date.now() - 1000 * 60 * 60 * 24 * 30, medianPrice: 27500000, medianPricePerM2: null, sampleSize: 17 },
    ],
    'sale|car|chevrolet|captiva|rm|santiago': [
        { ts: Date.now() - 1000 * 60 * 60 * 24 * 120, medianPrice: 6400000, medianPricePerM2: null, sampleSize: 8 },
        { ts: Date.now() - 1000 * 60 * 60 * 24 * 90, medianPrice: 6550000, medianPricePerM2: null, sampleSize: 9 },
        { ts: Date.now() - 1000 * 60 * 60 * 24 * 60, medianPrice: 6680000, medianPricePerM2: null, sampleSize: 11 },
        { ts: Date.now() - 1000 * 60 * 60 * 24 * 30, medianPrice: 6820000, medianPricePerM2: null, sampleSize: 10 },
    ],
};
